### ISSUE TITLE
Data Collection

### ISSUE THREAD

**Issue by Jbwasse2** [Jbwasse2/topological-mapping#5]
ROS Nodes around the sensors of the robot for collecting data
- Camera (Done)
- LIDAR (Issue #10 )
- Depth (TODO), need to get camera on board robot

**Comment by Jbwasse2** [comment]
Camera is verified ceb80afcb8453d669122ea4495be715982af731a

**Comment by Jbwasse2** [comment]
At this point its just like whether I want to add a depth camera on the robot or not.

**Comment by Jbwasse2** [comment]
I asked Ruben to get the depth camera running on the robot. Can probably tape it down?

**Comment by dorianisnairod** [comment]
Cannot find the GPU component within the bot. Will implement the CPU version of the zedcam

**Comment by dorianisnairod** [comment]
CPU version implemented. 
![image](https://user-images.githubusercontent.com/42956126/123467853-97a6fe80-d5b6-11eb-9f0f-44d003c391fd.png)
Runs by `calling roslaunch zed_cpu_ros camera_calibration.launch`
Unsure if this is the final step.
